version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - ${ROOT_PORT}:${ROOT_PORT}
    restart: always
    networks:
      - main-network

  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - main-network

volumes:
  pg_data:

networks:
  main-network:
    driver: bridge
